# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Förderverein Pfarrzentrum St. Martin Cochem e.V.
email: pfarrzentrum@unsercochem.de
description: Unser Pfarrhaus im Herzen der Stadt Cochemn muss erhalten bleiben, es soll zu einem zukunftsfähigen Pfarrzentrum ausgebaut werden.
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unsercochem.de" # the base hostname & protocol for your site

collections:
  sections:
    output: false
  news:
    output: true
    layout: detail
  events:
    output: true
    layout: news

defaults:
  - scope:
      path: "_news"
      type: news
    values:
      layout: detail
  - scope:
      path: "_events"
      type: events
    values:
      layout: event

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

gems:
  - jekyll-seo-tag

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - "*.conf"
  - ".idea/*"
